<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>row1_More_li_HMOID</name>
   <tag></tag>
   <elementGuidId>7b57056f-ad75-4b18-997a-fc1f99e5fe7d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HMOID: H0087</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/mrrc-qa-open[1]/section[1]/table[@class=&quot;table-mrrc-portal&quot;]/tbody[1]/tr[2]/td[1]/ul[@class=&quot;list-inline&quot;]/li[1]</value>
   </webElementProperties>
</WebElementEntity>
