<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table_2nd Contract on table</name>
   <tag></tag>
   <elementGuidId>353ec3c3-39ec-46c1-8597-f4c9469d705c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/ng-component[1]/main[1]/mrrc-open[1]/section[1]/table[@class=&quot;table-mrrc-portal&quot;]/tbody[1]/tr[3]/td[1]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ng-component[1]/main[1]/mrrc-open[1]/section[1]/table[@class=&quot;table-mrrc-portal&quot;]/tbody[1]/tr[3]/td[1]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
