<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1_coversheet_ID</name>
   <tag></tag>
   <elementGuidId>7fc59c10-406b-483c-9dc5-423c5ef95d02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mainContent)/mrrc-open[1]/section[1]/table[1]/tbody[1]/tr[1]/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent)/mrrc-open[1]/section[1]/table[1]/tbody[1]/tr[1]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
