<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td</name>
   <tag></tag>
   <elementGuidId>68e5d5a4-79f7-48ed-9a85-169335fde464</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/rm-search[@class=&quot;search-collapsed&quot;]/section[@class=&quot;container-fluid&quot;]/table[1]/tbody[1]/tr[@class=&quot;shown&quot;]/td[7]</value>
   </webElementProperties>
</WebElementEntity>
