<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Small</name>
   <tag></tag>
   <elementGuidId>af121694-20e8-40af-a476-d6e30b6892c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/main[1]/mrrc-submission[1]/mrrc-submission-review[1]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/section[@class=&quot;thumbnail-small&quot;]/sticky[@class=&quot;tools&quot;]/div[1]/ul[1]/li[1]/button[@class=&quot;active&quot;][count(. | //button[@ng-reflect-ng-class = '[object Object]' and (text() = 'Small' or . = 'Small')]) = count(//button[@ng-reflect-ng-class = '[object Object]' and (text() = 'Small' or . = 'Small')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Small</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/mrrc-submission[1]/mrrc-submission-review[1]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/section[@class=&quot;thumbnail-small&quot;]/sticky[@class=&quot;tools&quot;]/div[1]/ul[1]/li[1]/button[@class=&quot;active&quot;]</value>
   </webElementProperties>
</WebElementEntity>
