<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table_first coversheet_a_Contract-Level RADV</name>
   <tag></tag>
   <elementGuidId>d5544d76-b281-459c-888d-7f5a54c4bfef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/main[1]/mrrc-open[1]/section[@class=&quot;container-fluid&quot;]/table[@class=&quot;table-mrrc-portal&quot;]/tbody[1]/tr[1]/td[@class=&quot;coversheet&quot;]/a[1][count(. | //a[(contains(text(), ' Contract-Level RADV') or contains(., ' Contract-Level RADV'))]) = count(//a[(contains(text(), ' Contract-Level RADV') or contains(., ' Contract-Level RADV'))])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value></value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mrrc/submission/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/mrrc-open[1]/section[@class=&quot;container-fluid&quot;]/table[@class=&quot;table-mrrc-portal&quot;]/tbody[1]/tr[1]/td[@class=&quot;coversheet&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
