<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table_th_More</name>
   <tag></tag>
   <elementGuidId>6b294316-8cbb-4025-8503-e1c2c048994b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/main[1]/mrrc-open[1]/section[@class=&quot;container-fluid&quot;]/table[@class=&quot;table-mrrc-portal&quot;]/thead[1]/tr[1]/th[1][count(. | //th[(text() = 'More' or . = 'More')]) = count(//th[(text() = 'More' or . = 'More')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>more</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>More</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/mrrc-open[1]/section[@class=&quot;container-fluid&quot;]/table[@class=&quot;table-mrrc-portal&quot;]/thead[1]/tr[1]/th[1]</value>
   </webElementProperties>
</WebElementEntity>
