<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>INV3_label_Other</name>
   <tag></tag>
   <elementGuidId>ef6b0835-1c2a-4ec1-b567-a7c9ca4c3311</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>inv3Response22</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Other</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section7&quot;)/div[1]/div[@class=&quot;invalid ng-dirty ng-touched ng-invalid&quot;]/div[@class=&quot;options&quot;]/ul[@class=&quot;two-column&quot;]/li[@class=&quot;ng-dirty ng-touched ng-invalid&quot;]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
