<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HCC_Tab1_ICD9_codes</name>
   <tag></tag>
   <elementGuidId>abc14e86-38c1-44b1-96a7-35acc3d8068d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mainContent&quot;)/plan-add-coversheet[1]/add-coversheet-wizard[1]/section[1]/div[1]/div[1]/div[@class=&quot;step-4&quot;]/ul[1]/li[1]/label[1]/small[1]/text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>starts with</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                HCC
          </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/plan-add-coversheet[1]/add-coversheet-wizard[1]/section[1]/div[1]/div[1]/div[@class=&quot;step-4&quot;]/ul[1]/li[1]/label[1]/small[1]</value>
   </webElementProperties>
</WebElementEntity>
