<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_icon-question-circle</name>
   <tag></tag>
   <elementGuidId>10516a6a-82b4-4a81-baa4-f8088d5d2ca8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-question-circle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/mrrc-pm-reset[1]/section[1]/div[@class=&quot;table-header&quot;]/form[@class=&quot;search ng-untouched ng-pristine ng-invalid&quot;]/span[@class=&quot;trigger&quot;]/span[@class=&quot;icon-question-circle&quot;]</value>
   </webElementProperties>
</WebElementEntity>
