<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TimeLine_Text_2_h3</name>
   <tag></tag>
   <elementGuidId>9bf69182-5275-427c-8bdd-357a29ba5f77</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timeline&quot;)/ol[@class=&quot;timeline&quot;]/li[2]/div[1]/header[1]/h3[1]</value>
   </webElementProperties>
</WebElementEntity>
