<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>More_title_h4_Coversheets</name>
   <tag></tag>
   <elementGuidId>e08a94f2-82ba-4c21-8049-5ff8a487497d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;planList&quot;)/tr[2]/td[1]/div[1]/div[1]/h4[2][count(. | //h4[(text() = 'Coversheets' or . = 'Coversheets')]) = count(//h4[(text() = 'Coversheets' or . = 'Coversheets')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Coversheets</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;planList&quot;)/tr[2]/td[1]/div[1]/div[1]/h4[2]</value>
   </webElementProperties>
</WebElementEntity>
