<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>More_HCC-2_Title_span_HCC</name>
   <tag></tag>
   <elementGuidId>90982a3b-5d4d-4ac0-81d7-e66b37792504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;planList&quot;)/tr[2]/td[1]/div[1]/div[3]/ul[@class=&quot;list-unstyled&quot;]/li[2]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HCC19/19:</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;planList&quot;)/tr[2]/td[1]/div[1]/div[3]/ul[@class=&quot;list-unstyled&quot;]/li[2]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
