<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date_OutPatient_dates</name>
   <tag></tag>
   <elementGuidId>e47fe7cb-ca05-480c-941e-46c330c8fba3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;add-coversheet-wizard-divOutpatient&quot;)[count(. | //*[@id = 'add-coversheet-wizard-divOutpatient']) = count(//*[@id = 'add-coversheet-wizard-divOutpatient'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-coversheet-wizard-divOutpatient</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dates</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-coversheet-wizard-divOutpatient&quot;)</value>
   </webElementProperties>
</WebElementEntity>
