<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date_Inpatient_Dates</name>
   <tag></tag>
   <elementGuidId>e338db78-d8ac-4238-803b-8e364d879a8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;add-coversheet-wizard-divInpatient&quot;)[count(. | //*[@id = 'add-coversheet-wizard-divInpatient']) = count(//*[@id = 'add-coversheet-wizard-divInpatient'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-coversheet-wizard-divInpatient</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dates</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-coversheet-wizard-divInpatient&quot;)</value>
   </webElementProperties>
</WebElementEntity>
