<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_h5_Name</name>
   <tag></tag>
   <elementGuidId>24a742cc-4f47-4c45-a505-7494be2d6f9b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/plan-coversheet-detail[1]/section[@class=&quot;enrollee-wizard review&quot;]/div[@class=&quot;row text-center&quot;]/div[@class=&quot;col-xs-6 col-sm-4 col-sm-4 col-sm-offset-2 col-md-3 col-md-offset-3&quot;]/h5[1]</value>
   </webElementProperties>
</WebElementEntity>
