<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Type</name>
   <tag></tag>
   <elementGuidId>a0d02b06-68ba-493f-a623-6fd96b8098e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mainContent&quot;)/coversheet-list[1]/section[1]/table[1]/thead[1]/tr[1]/th[2][count(. | //th[(text() = 'Type' or . = 'Type')]) = count(//th[(text() = 'Type' or . = 'Type')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Type</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/coversheet-list[1]/section[1]/table[1]/thead[1]/tr[1]/th[2]</value>
   </webElementProperties>
</WebElementEntity>
