<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tr_1_td_8_More - Remove Coversheet</name>
   <tag></tag>
   <elementGuidId>4595861e-42ed-44c4-82cb-d774daeebd8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mainContent&quot;)/coversheet-list[1]/section[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/div[4]/p[2]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/coversheet-list[1]/section[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/div[4]/p[2]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
