<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tr_1_td_8_More - Opt In Automated</name>
   <tag></tag>
   <elementGuidId>aa21d5bf-7e83-4a93-92a0-241f144b89e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/ng-component/main[1]/coversheet-list[1]/section[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/div[6]/p[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ng-component/main[1]/coversheet-list[1]/section[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/div[6]/p[1]</value>
   </webElementProperties>
</WebElementEntity>
