<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Thead_button_Progress</name>
   <tag></tag>
   <elementGuidId>99123ce0-eb76-457c-a0f5-5e465ee19799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/ng-component/main[1]/plan-portal[1]/section[1]/table[@class=&quot;table-contracts&quot;]/thead[1]/tr[1]/th[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Progress</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ng-component/main[1]/plan-portal[1]/section[1]/table[@class=&quot;table-contracts&quot;]/thead[1]/tr[1]/th[1]</value>
   </webElementProperties>
</WebElementEntity>
