<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Err_Msg_Other_Comment_overLimit</name>
   <tag></tag>
   <elementGuidId>cdf55d24-13b4-4d0c-89dd-c18d0d75a1f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section3&quot;]/div/div/div[3]/errors[2]/small</value>
   </webElementProperties>
</WebElementEntity>
